clone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("instagram.urls")),
]

instagram/urls.py
from django.urls import path
from.import views
from .views import index_view, form_submit

app_name = "instagram"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.sign_up, name="sign_up"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path ("", views.index_view, name=" profile_view"),
    path ("submit/", form_submit, name="profile_submit"),
]

instagram/models.py
from django.db import models

# Create your models here.

class profile(models.Model):
    name= models.CharField (max_length=15, blank=False)
    bio= models.TextField ()

# def __str__(self):
#     return f'profile from {self.name}, bio: {self.bio}'
    

instagram/forms.py
from django import forms

from .models import profile

class profileForm(forms.ModelForm):
    name = forms.CharField(
        error_messages={'required': 'Please let us know what to call you!'}
    )
    class Meta:
        model = profile
        fields = '__all__'

        labels = {
            "name": "Your name",
            "bio": 'Your description',
        }
        

instagram/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import profileForm

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index (request):
    return render(request, "instagram/index.html")


def sign_up(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('instagram:index')) 
        return render(request, "instagram/instagram_signup.html")
    elif request.method == "POST":
        user = User.objects.create_user(
            username=request.POST.get('username'),
            email=request.POST.get('email'),
            password=request.POST.get('password'),
        )
        return HttpResponseRedirect(reverse('instagram:login')) 

def login_view(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('instagram:index')) 
        return render(request, "instagram/instagram_login.html")
    elif request.method == "POST":
        username = request.POST.get('username') # POST["username"]
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('instagram:index')) 
        else:
            return render(request, "instagram/instagram_login.html", {"login_message": "Username/password is incorrect"})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('instagram:login')) 


def index_view (request):
    profile = profileForm()
    return render(request, 'instagram/index.html', { 'form': profile })

def form_submit(request):
    form = profileForm(request.POST)
    if form.is_valid():
        form.save()
        return render(request, 'instagram/thank-you.html', {})
    else:
        return render(request, 'instagram/index.html', {'form': form})

instagram/templates/instagram/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Profile </title>
    <link rel="stylesheet" href={% static "instagram/style.css" %}>
</head>

<body>
    {% if has_error %}
        {{has_error}}
    {% endif %}    

    <form action="/submit/" method="POST" class="form">
        {% csrf_token %}
        {{form}}
        <input type="submit">
        
    </form>
</body>

</html>

instagram/templates/instagram/instagram_login.html
<h1> Login </h1>
<form action="{% url 'instagram:login' %}" method="post">
    {% csrf_token %}
    {% if login_message %}<p style="color: red"><strong>{{ login_message }}</strong></p>{% endif %}
    <label for="username">Username: </label>
    <input type="text" value="" name="username"> <br/><br/>
    <label for="email">Password: </label>
    <input type="password" value="" name="password"> <br/><br/>
    <input type="submit" value="Login" id="login">
</form>

instagram/templates/instagram/instagram_signup.html
<h1> Register </h1>
<form action="{% url 'instagram:sign_up' %}" method="post">
    {% csrf_token %}
    {% if register_message %}<p style="color: red"><strong>{{ register_message }}</strong></p>{% endif %}
    <label for="fname">First name: </label>
    <input type="text" value="" name="fname"> <br/><br/>
    <label for="lname">Last Name: </label>
    <input type="text" value="" name="lname"> <br/><br/>
    <label for="email">Email: </label>
    <input type="email" value="" name="email"> <br/><br/>
    <label for="username">Username: </label>
    <input type="text" value="" name="username"> <br/><br/>
    <label for="password">Password: </label>
    <input type="password" value="" name="password"> <br/><br/>
    <input type="submit" value="Register" id="register">
</form>

instagram/templates/instagram/thank-you.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thank you</title>
</head>
<body>
    Submit <a href={% url "profile_view" %}></a>
</body>
</html>